version: "2"

services:
    keycloak1:
        container_name:                 mikeycloak1 
        build:                          .                   # Generar una imagen de contenedor con las 
                                                            # instrucciones suministradas en el archivo Dockerfile
        image:                          mi-keycloak:1.0.0
        ports:
                                      - 8080:8080  
                                      - 8443:8443
        environment:
            KEYCLOAK_ADMIN:             admin
            KEYCLOAK_ADMIN_PASSWORD:    password
            KC_DB_URL:                  jdbc:postgresql://midb:5432/keycloak
            KC_DB_USERNAME:             keycloak
            KC_DB_PASSWORD:             password
        command:                        start-dev

    midb:
        container_name:                 mipostgres
        image:                          postgres:15.2
        environment:
            POSTGRES_USER:              keycloak
            POSTGRES_PASSWORD:          password
        volumes:
                                      - /home/ubuntu/environment/datos/postgresql:/var/lib/postgresql/data

    mi-email-server:                    # Esto es un Capturador de emails. Es un mock de un servidor de correo
        image:                          mailhog/mailhog
        container_name:                 mailhog
        ports:
                                      - 1025:1025
                                      - 8081:8025